version: "3"

services:
  vpn-server:
    image: strongx509/tnc-server:latest
    container_name: tnc-server
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_MODULE
    stdin_open: true
    tty: true
    volumes:
      - ./server:/etc/swanctl
      - ./strongswan.conf.server:/etc/strongswan.conf
      - ./tnc_config.server:/etc/tnc_config
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./settings.ini:/etc/strongTNC/settings.ini
      - ./init_tnc:/usr/local/bin/init_tnc
      - ./tmp:/tmp
    networks:
      internet:
         ipv4_address: 192.168.0.2
      intranet:
         ipv4_address: 10.1.0.2
  vpn-client:
    image: strongx509/tnc-client:latest
    container_name: tnc-client
    depends_on:
      - vpn-server
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_MODULE
    stdin_open: true
    tty: true
    volumes:
      - ./client:/etc/swanctl
      - ./strongswan.conf.client:/etc/strongswan.conf
      - ./tnc_config.client:/etc/tnc_config
      - ./tmp:/tmp
    networks:
      internet:
         ipv4_address: 192.168.0.3

networks:
  internet:
    ipam:
      driver: default 
      config:
        - subnet: 192.168.0.0/24
  intranet:
     ipam:
        driver: default
        config:
          - subnet: 10.1.0.0/16 
